### ISSUE TITLE
Solo3 failed to build on 10.10.2

### ISSUE THREAD

**Issue by mmf24** [ncareol/homebrew-lrose-solo3#1]
Tried upgrading solo3 from an older version installed a few months ago; Solo3 wouldn't build and the old version of Solo3 won't run anymore, maybe from an updated dependency?

Gist: https://gist.github.com/anonymous/8cdfa21e0fb73101c0b3

**Comment by vanandel** [comment]
Apparently the homebrew maintainers don't want to support the X11 backend of Gtk anymore, which solo3 relies on.  See
https://github.com/Homebrew/homebrew/pull/39868 

I am very sorry, but we have almost no resources to support solo3.  This change by the homebrew developers makes it impossible to support solo3 with homebrew for the immediate future.  

In theory, someone could modify solo3 to use the Quartz backend of Gtk, but I don't know when anyone will have time to do that.

**Comment by burghart** [comment]
As of version 20160613, solo3 now builds using the Quartz backend of Gtk.
