### ISSUE TITLE
mac OS10.11 install solo3 error

### ISSUE THREAD

**Issue by zhuwenjian** [ncareol/homebrew-lrose-solo3#3]
when the step 3 "brew install solo3", i got the following errors,

Last 15 lines from /Users/kevin/Library/Logs/Homebrew/solo3/02.make:
/usr/local/Cellar/libsigc++/2.8.0/include/sigc++-2.0/sigc++/functors/slot.h:222:151: error: a space is required between consecutive right angle brackets (use '> >')
      return (typed_rep->functor_).SIGC_WORKAROUND_OPERATOR_PARENTHESES<type_trait_take_t<T_arg1>, type_trait_take_t<T_arg2>, type_trait_take_t<T_arg3>>
                                                                                                                                                      ^~
                                                                                                                                                      > >
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [ASpeckleCmd.o] Error 1
make[1]: *** Waiting for unfinished jobs....
20 errors generated.
20 errors generated.
make[1]: *** [AddValueCmd.o] Error 1
make[1]: *** [AddFieldCmd.o] Error 1
20 errors generated.
make[1]: *** [AbsoluteValueCmd.o] Error 1
make: *** [install-recursive] Error 1

**Comment by mike-dixon** [comment]
Can you send me a copy of

/usr/local/Cellar/libsigc++/2.8.0/include/sigc++-2.0/sigc++/functors/slot.h

on your host?

Thanks

Mike

**Comment by zhuwenjian** [comment]
I am very appreciate that you deal with my problem. Thanks!

**Comment by mike-dixon** [comment]
Hi

Sorry for the confusion.

I need you to send me a copy of the following file:

/usr/local/Cellar/libsigc++/2.8.0/include/sigc++-2.0/sigc++/functors/slot.h

as it is installed on your system.

Thanks

Mike

**Comment by abkenyon** [comment]
Hello Mike, 

I am having the same error. It appears this issue was not solved. Would you like me to send you a copy of the slot.h file on my system?

**Comment by mike-dixon** [comment]
Chris

When you get a chance, could  you help this person out?

Thanks

Mike


-------- Forwarded Message --------
Subject: 	Re: [ncareol/homebrew-lrose-solo3] mac OS10.11 install solo3 
error (#3)
Date: 	Mon, 06 Jun 2016 13:18:24 -0700

**Comment by zhuwenjian** [comment]
sorry, my problem has not yet been solved!

**Comment by burghart** [comment]
The problem appears to be with libsigc++ 2.8.0, since the solo3 build works with libsigc++ 2.4.0. I hope to have a resolution to the problem soon.

**Comment by burghart** [comment]
I believe I have finally fixed this issue. The libsigc++ issue led to a small chain of other problems, but all have been resolved. For those who got to `brew install solo3` and then had it fail, the following should now work for you:
```
$ brew update
$ brew install solo3
```

**Comment by mike-dixon** [comment]
Chris - thanks - Mike
